[build]
  command = "composer install && php artisan build" # Sesuaikan dengan perintah build Laravel Anda

[context.production.environment]
  PHP_VERSION = "8.1"

[context.deploy-preview.environment]
  PHP_VERSION = "8.1"

[context.branch-deploy.environment]
  PHP_VERSION = "8.1"

[build.environment]
  COMPOSER_FLAGS = "--optimize-autoloader --no-dev"

[build.environment]
  NPM_FLAGS = "--production --no-optional"

publish = "public" # Ubah menjadi folder publik Laravel yang sesuai
