[build]
  command = "composer install && php artisan build"
  publish = "dist/"

[context.production.environment]
  PHP_VERSION = "8.1"

[context.deploy-preview.environment]
  PHP_VERSION = "8.1"

[context.branch-deploy.environment]
  PHP_VERSION = "8.1"

[build.environment]
  COMPOSER_FLAGS = "--optimize-autoloader --no-dev"
  NPM_FLAGS = "--production --no-optional"

publish = "public"
